name: Build
on:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Set branch
        run: sed -i 's/<project.branch><\/project.branch>/<project.branch>master<\/project.branch>/' pom.xml
      - name: Build
        run: mvn package --file pom.xml -Dproject.branch=coreprotect
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: CoreProtect
          path: target/CoreProtect-*.jar
          exclude-hidden-files: true
